project:
  type: website
  output-dir: docs
  resources: CNAME

website:
  title: "R. Teal Witter"

format:
  html:
    theme: [cosmo, custom_theme.scss]
    css: styles.css
    toc: false
    include-in-header: header.html
